### PR TITLE
👀 iPhone X support

### PR DESCRIPTION
**Pull request by lukemartin**
Before:

screen shot 2017-11-20 at 16 52 46

After:

screen shot 2017-11-20 at 16 53 11

### CODE REVIEW

**Comment by lukemartin** [comment]
@peduarte it looks like the increased width makes it display at a different breakpoint. An unintended side-effect of changing the viewport setting 🤔

**Comment by peduarte** [comment]
@lukemartin thanks man. What do you think? Looking at the screen shot, the latter looks a bit weird - it has lost balance and looks disproportional. Probably related to your comment above.

**Comment by lukemartin** [comment]
@peduarte I think they both look weird :s

**Comment by ibrennan** [comment]
Need to change the bounds of a medium width site here: https://github.com/fathomlondon/fathomlondon.github.io/blob/develop/_sass/_variables.scss#L2

My suggestion is maybe also add a min-height to media queries to capture devices in this orientation

**Comment by lukemartin** [comment]
Made @ibrennan's suggested change to the breakpoints which improves the balance a lot:

image

**Comment by peduarte** [comment]
👍

**Pull request merged**
