### PR TITLE
✨ Add client logos

### PR DESCRIPTION
**Pull request by artisologic**
I want to add the missing svg icon before merging.

### CODE REVIEW

**Comment by peduarte** [comment]
I think this is ok but I can't help but think it feels a bit weird to create a `ClientLogo` *Component*.

To me a Component should be reusable and this is not a truly reusable component, right? 

I wonder if a better Component would be `Client Logos` and then inside that just have all the images.

```
<div class="ClientLogos">
    <img class="" src="...">
    <img class="" src="...">
    <img class="" src="...">
</div>
```

Not a biggie, happy to have it like this for now and then we can talk about it tomorrow and see if we can improve this.

**Comment by artisologic** [comment]
@peduarte Yeah I mean, I managed to get everything done with the atomic classes I just needed a few extra things, really I could do it all by adding a few flex helpers but the thing that remained was the `min-height: 7.5rem` I don't know where to put it.

**Comment by peduarte** [comment]
Yeah I see what you mean! We've gotta find a better way. I know Tachyons has some `height` helpers - maybe we could add some too?

But in any case, do you find it weird that we just have loads o `ClientLogos` without them being wrapped in a `div` or something? Would it break if you had an off number logos?

**Comment by artisologic** [comment]
Nah it wouldn't break but yeah it is kinda weird. Maybe I should go with your approach? `ClientLogos > div`?

**Comment by artisologic** [comment]
I think I'll give this a go

**Pull request merged**
